#!/bin/sh
mvn clean package
docker build -t kenilgondaliya/MSAClient2 .
docker rm -f MSAClient2 2>/dev/null || true
docker run -it --name MSAClient2 -p 8080:8080 --name MSAClient2 kenilgondaliya/MSAClient2
