#!/bin/sh
mvn clean package
docker build -t kenilgondaliya/GarmentClient .
docker rm -f GarmentClient 2>/dev/null || true
docker run -it --name GarmentClient -p 8080:8080 --name GarmentClient kenilgondaliya/GarmentClient
