
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


mp.jwt.verify.issuer=airhacks
mp.jwt.verify.publickey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtQjO5HbGIFYGgRMaR2GlYSq/m7mFt7d+fcS99fL4W1NuG1zUvYC2E0fCsAws6OlAGEb00c3zELpSam1cmiboCr3R2SK+VlonIY2psDwsUCDRsAZ+59TwNyoJSkaQaDkAAqDtWsi7yBwvCnIAIn76boL3bCcGQd7gTOqNIY/86ENAu+eRrSxf+HQHHlVmFPD382eTEthp98Ytf6Le9KJEyTtFhpyWxSNaE2eSlJiC9jq4euWFee2+PL7wTW/WdSB3eHbiuRqnA9ok0JBMR/iLLawfnK1tcu0dFDeDgxBqgJfwbW1IG1RM9bi0Q7bb1HSOOb7lksbnrA2LSQdjw/VlrQIDAQAB
