#!/bin/sh
mvn clean package
docker build -t kenilgondaliya/MSAClient .
docker rm -f MSAClient 2>/dev/null || true
docker run -it --name MSAClient -p 8080:8080 --name MSAClient kenilgondaliya/MSAClient
