
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


myclient/mp-rest/url=http://localhost:8085/MSAApp/rest/example

jwt-string=eyJraWQiOiJqd3Qua2V5IiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkdWtlIiwidXBuIjoiZHVrZSIsImF1dGhfdGltZSI6MTc4NTI3MzI4MiwiaXNzIjoiYWlyaGFja3MiLCJncm91cHMiOlsiY2hpZWYiLCJoYWNrZXIiXSwiZXhwIjoxNzg1Mjc0MjgyLCJpYXQiOjE3ODUyNzMyODIsImp0aSI6IjQyIn0.s2-Xzp-So4HpYr8sOTSTHdyZsQev2r6A5JDPrUyOynJz-cp0_FVN5yH6r4qDcfWlKGTcxSYgPJ9rkcdPu5az_vyLz1XnLRKXw4gO3Xmx_WkigqbQQH2exipb82jznVTXym2NE4k0h1GSl-Gi8NGzlseCLFxgpvktiHfIVFEim4hG5tZv1g8qu-w6_d9amtrT9gFV3NUIwv7oDPadqZdk5YRv-zieuqfkwhKoDCAG2stNY2qisuFRhtFOUVxiWTFxhJmJ2erRePE1ibgAKP9IZSDuJ-Yvs8K8MEV3M08eOXMdKzcpMczHVudvidAERjaDOyqrh7-rW158vqwv0ht7AA